"""creating relationships 3

Revision ID: 00422c6e43b7
Revises: f2348ea4a430
Create Date: 2022-06-04 15:05:36.520042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00422c6e43b7'
down_revision = 'f2348ea4a430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_artist',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_artist')
    # ### end Alembic commands ###
