"""relationship removed again again

Revision ID: 02cbbfcb1855
Revises: 37893bcb43ac
Create Date: 2022-06-03 15:01:23.266864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cbbfcb1855'
down_revision = '37893bcb43ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_venue_id_fkey', 'artist', type_='foreignkey')
    op.drop_column('artist', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artist_venue_id_fkey', 'artist', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
