"""reslving relationships 2

Revision ID: 2329e3ac8e10
Revises: 2aaf71e6c005
Create Date: 2022-06-04 14:34:19.351727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2329e3ac8e10'
down_revision = '2aaf71e6c005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_identifier', sa.Column('start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_identifier', 'start_time')
    # ### end Alembic commands ###
