"""final-1 resolving relationships

Revision ID: 2aaf71e6c005
Revises: 4b5145a9200c
Create Date: 2022-06-04 10:58:44.050362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaf71e6c005'
down_revision = '4b5145a9200c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'venue_id')
    # ### end Alembic commands ###
