"""removing child fk

Revision ID: 7a46e6d462d1
Revises: 2329e3ac8e10
Create Date: 2022-06-04 14:40:36.514317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a46e6d462d1'
down_revision = '2329e3ac8e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_venue_id_fkey', 'artist', type_='foreignkey')
    op.drop_column('artist', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artist_venue_id_fkey', 'artist', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
