"""added relationship

Revision ID: c68bf81115bb
Revises: 15d8a843ff77
Create Date: 2022-06-03 12:06:31.079716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68bf81115bb'
down_revision = '15d8a843ff77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'venue_id')
    # ### end Alembic commands ###
